### ISSUE TITLE
Az Function Embedding Service Proposed Updates

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/azure-search-openai-demo-csharp#203]
## User Flow

```mermaid
graph LR
    UI[User Interface] --> |Uploads document|Backend[Backend Service]
    Backend --> |Uploads document|Storage[Azure Blob Storage]
    Storage -->|Blob trigger| Function[Azure Function]
    Function -->|Generate embeddings and index document| Search[Azure Cognitive Search]
```

## Tasks

- [x] Fix 500 error thrown by `api/documents` endpoint with handler `OnPostDocumentAsync`

```text
System.Net.Http.HttpRequestException: TypeError: Failed to fetch ---> TypeError: Failed to fetch Exception_EndOfInnerExceptionStack at System.Net.Http.BrowserHttpInterop.d__13`1[[System.Runtime.InteropServices.JavaScript.JSObject, System.Runtime.InteropServices.JavaScript, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext() at System.Net.Http.BrowserHttpHandler.CallFetch(HttpRequestMessage , CancellationToken , Nullable`1 ) at System.Net.Http.BrowserHttpHandler.g__Impl|53_0(HttpRequestMessage , CancellationToken , Nullable`1 ) at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.g__Core|5_0(HttpRequestMessage , Boolean , CancellationToken ) at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.g__Core|5_0(HttpRequestMessage , Boolean , CancellationToken ) at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken ) at ClientApp.Services.ApiClient.UploadDocumentsAsync(IReadOnlyList`1 files, Int64 maxAllowedSize)
```

- [x] Deploy Azure Function to Azure
    - Should have access to all resources in the deployment, specifically OpenAI, Azure (Blob) Storage and Azure Cognitive Search
- [x] Create shared embedding service
    - Should use OpenAI embedding models to generate embeddings.
    - Should use Azure Cognitive Search instance to index documents
- [x] Update `AzureSearchEmbedService` (to bsaically do what PrepDocs is doing for chunking / embedding generation / indexing)
    - Should use shared embedding service to generate embeddings
    - Update SearchDocument schema to include embeddings
- [x] Update PrepDocs to only upload documents to Blob Storage. Let the Azure Function handle embedding generation and indexing.

**Comment by luisquintanilla** [comment]
## How to (manually) test

1. In the Azure portal, navigate to the storage account tied to the deployment.
2. Use the Storage Browser to upload your file to the `content` blob container. 

    ![image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/46974588/aa770ec8-b13c-49ec-ba10-6ed730b678d5)

    This assumes that you used the default azure storage container. Otherwise, use the value of AZURE_STORAGE_CONTAINER set in the *.env* file.

**Comment by igrgurina** [comment]
This would be incredibly useful

**Comment by luisquintanilla** [comment]
Marking this issue as complete since this service now lives in the [EmbedFunctions project](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/tree/main/app/functions/EmbedFunctions).
