### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LittleLittleCloud** [Azure-Samples/azure-search-openai-demo-csharp#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Current TODO lists in my mind is

- [x] Convert MVC backend to minimal API
- [x] Configure codespace && devContainer && adding to README.md page
- [x] Adding the rest of retrieval-read methods in backends
- - [x] /chat (wip - xiaoyuz)
- - [x] /ask ReadRetrieveRead
- - [x] /ask ReadDecomposeAsk

And feel free to make any CURD changes on that list
