### ISSUE TITLE
To-Do improvements

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/azure-search-openai-demo-csharp#40]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

- [x] https://github.com/Azure-Samples/azure-search-openai-demo-csharp/issues/20
- [x] #52
- [x] #44
- [x] #42
- [ ] #53
- [x] #50
- [ ] #45
- [x] #46
- [ ] #47
- [x] #48
- [x] #49
- [x] #58
- [x] #60

**Comment by luisquintanilla** [comment]
Closing in favor of #123
